### ISSUE TITLE
Missing CHANGELOG for JANE

### ISSUE THREAD

**Issue by muppetjones** [powerman/asciidoc-cheatsheet#2]
The change log should contain the following sections (if relevant) for each version update:
- Added
- Changed
- Deprecated
- Fixed
- Removed
- Security

Also, the change log should maintain an 'Unreleased' section for keeping track of known changes that are in the works. _This should most likely reflect open issues._

See http://keepachangelog.com/en/0.3.0/

**Comment by muppetjones** [comment]
Sorry--accidentally switched to the wrong window. Completely different project.

**Comment by powerman** [comment]
No prob, it was interesting to read that website. There are actually similar standards, for example this one if for perl: https://metacpan.org/pod/distribution/CPAN-Changes/lib/CPAN/Changes/Spec.pod (and there are tools to convert it to markdown, like https://metacpan.org/release/CPAN-Changes-Markdown).
